Add mediawiki.api dependency to ext.wikisource.OCR
OcrTool.js is using mw.Api (since b4f29d2d64)

qunit tests shows sometimes:
Uncaught TypeError: api.saveOption is not a function

Change-Id: Ib8276e203d13849b321b161d626df71dc773874b